//! Hybrid search engine.
//!
//! Four retrievers, one result list:
//!
//! | strategy | index | good at |
//! |---|---|---|
//! | keyword  | FTS5 BM25                    | precise multi-word queries |
//! | fuzzy    | FTS5 trigram + edit distance | typos, partial words |
//! | semantic | dense vectors                | "I can't remember the words" |
//! | filter   | B-tree                       | `tag:` / `type:` / `year:` narrowing |
//!
//! Their scores live on incomparable scales, so results are combined by
//! reciprocal rank fusion rather than hand-tuned score normalisation.


pub mod fusion;
pub mod lexical;
pub mod parse;
pub mod vector;

use std::collections::{HashMap, HashSet};
use std::sync::Arc;

use async_trait::async_trait;
use parking_lot::RwLock;
use rusqlite::{params, params_from_iter, Connection};
use yk_ai::EmbeddingProvider;
use yk_core::ports::SearchIndex;
use yk_core::query::*;
use yk_core::{text, Error, Key, Result};
use yk_store::filter::Predicate;
use yk_store::{sql_err, write_tx, Db, Store};

pub use yk_ai::{LocalEmbedder, OpenAiEmbedder};
use fusion::RankedList;
use vector::VectorStore;

/// How many candidates each retriever contributes before fusion.
const CANDIDATES: usize = 300;

/// How wide the structural set has to be when it is a *restriction* rather
/// than the answer: the ranked legs draw from the whole library, so a hit can
/// sit anywhere in it.
const CANDIDATE_SET: usize = 20_000;
/// Minimum edit-distance similarity for a fuzzy hit to count.
const FUZZY_FLOOR: f32 = 0.45;
/// Rows written per background transaction. Small on purpose — see
/// `embed_pending`.
const WRITE_CHUNK: usize = 200;

const W_KEYWORD: f32 = 1.0;
const W_SEMANTIC: f32 = 0.9;
const W_FUZZY: f32 = 0.55;

pub struct SearchEngine {
    store: Store,
    db: Db,
    embedder: Arc<dyn EmbeddingProvider>,
    vectors: Arc<RwLock<VectorStore>>,
}

impl SearchEngine {
    /// Build an engine and warm the vector cache from disk.
    pub fn new(store: Store, embedder: Arc<dyn EmbeddingProvider>) -> Result<Self> {
        let db = store.db().clone();
        let engine = Self {
            store,
            db,
            vectors: Arc::new(RwLock::new(VectorStore::new(embedder.dimensions()))),
            embedder,
        };
        engine.load_vectors()?;
        Ok(engine)
    }

    /// Load only vectors produced by the *current* provider and dimensionality;
    /// anything else is stale and will be regenerated by the embedding worker.
    fn load_vectors(&self) -> Result<usize> {
        let conn = self.db.conn()?;
        let mut stmt = conn
            .prepare(
                "SELECT item_id, library_id, vec FROM item_vectors \
                 WHERE provider = ?1 AND dim = ?2",
            )
            .map_err(sql_err)?;
        let mut cache = self.vectors.write();
        cache.reset(self.embedder.dimensions());
        let mut n = 0;
        let mut rows = stmt
            .query(params![self.embedder.id(), self.embedder.dimensions() as i64])
            .map_err(sql_err)?;
        while let Some(r) = rows.next().map_err(sql_err)? {
            let blob: Vec<u8> = r.get(2).map_err(sql_err)?;
            if let Some(v) = decode(&blob, self.embedder.dimensions()) {
                cache.upsert(r.get(0).map_err(sql_err)?, r.get(1).map_err(sql_err)?, &v);
                n += 1;
            }
        }
        tracing::debug!(vectors = n, provider = self.embedder.id(), "vector cache warmed");
        Ok(n)
    }

    /// The most semantically similar items to one already in the library.
    ///
    /// Uses the item's own stored vector rather than re-embedding its text: the
    /// vector is already there, embedding costs a network round trip, and an
    /// item whose text has changed since it was embedded should be compared as
    /// the index sees it — otherwise the graph and the search results disagree.
    ///
    /// Returns nothing at all when the item has no vector yet, which is honest:
    /// "not embedded" is not "nothing is similar".
    pub fn similar(&self, library_id: i64, item_id: i64, k: usize) -> Vec<(i64, f32)> {
        let vectors = self.vectors.read();
        let Some(query) = vectors.get(item_id).map(|v| v.to_vec()) else {
            return Vec::new();
        };
        vectors
            .search(library_id, &query, k + 1, None)
            .into_iter()
            .filter(|(id, _)| *id != item_id)
            .take(k)
            .collect()
    }

    /// Item ids permitted by the structural filter, or `None` when the filter
    /// adds nothing beyond "this library, not trashed" — which every retriever
    /// already enforces in SQL.
    ///
    /// Returns them ordered so a pure filter query (`tag:survey` with no text)
    /// can reuse the same scan instead of running it twice.
    /// The ids a structural filter allows, or `None` when nothing narrows it.
    ///
    /// `want` is how many are actually going to be used. When the query has no
    /// words the ids *are* the answer, in order, and only a page of them is
    /// wanted; when there are words they are a set the ranked legs get filtered
    /// against, and it has to be wide enough to contain the hits. Fetching
    /// twenty thousand either way meant `tag:survey` read 20,000 rows to return
    /// fifty.
    fn allowed(
        conn: &Connection,
        filter: &ItemFilter,
        want: Option<usize>,
    ) -> Result<Option<Vec<i64>>> {
        let structural = filter.collection.is_some()
            || !filter.tags.is_empty()
            || !filter.item_types.is_empty()
            || filter.keys.is_some()
            || filter.since.is_some()
            || filter.top_level_only
            || filter.trash != TrashScope::Exclude;
        if !structural {
            return Ok(None);
        }
        Ok(Some(Self::matching_ids(conn, filter, want.unwrap_or(CANDIDATE_SET))?))
    }

    fn matching_ids(conn: &Connection, filter: &ItemFilter, limit: usize) -> Result<Vec<i64>> {
        let collections = match &filter.collection {
            Some(key) => Some(resolve_collection_ids(conn, filter, key)?),
            None => None,
        };

        // The same choice `items::list` makes, through the same function — but
        // there the exact total is already in hand and here it is not, so the
        // tag is counted only as far as the crossover.
        let p = Predicate::for_page(conn, filter, collections.as_deref(), limit as i64, None);
        let hint = p.index_hint(SortField::DateModified);

        let sql = format!(
            "SELECT i.id FROM items i {hint} WHERE {} ORDER BY i.date_modified DESC LIMIT {limit}",
            p.sql
        );
        let mut stmt = conn.prepare_cached(&sql).map_err(sql_err)?;
        let out = stmt
            .query_map(params_from_iter(p.params.iter()), |r| r.get(0))
            .map_err(sql_err)?
            .collect::<rusqlite::Result<Vec<i64>>>()
            .map_err(sql_err);
        out
    }
}

fn resolve_collection_ids(conn: &Connection, filter: &ItemFilter, key: &Key) -> Result<Vec<i64>> {
    let sql = if filter.recursive {
        "WITH RECURSIVE sub(id) AS (
            SELECT id FROM collections WHERE library_id = ?1 AND key = ?2
            UNION ALL SELECT c.id FROM collections c JOIN sub ON c.parent_id = sub.id
         ) SELECT id FROM sub"
    } else {
        "SELECT id FROM collections WHERE library_id = ?1 AND key = ?2"
    };
    let mut stmt = conn.prepare_cached(sql).map_err(sql_err)?;
    let out = stmt
        .query_map(params![filter.library_id, key.as_str()], |r| r.get(0))
        .map_err(sql_err)?
        .collect::<rusqlite::Result<Vec<i64>>>()
        .map_err(sql_err);
    out
}

fn encode(v: &[f32]) -> Vec<u8> {
    v.iter().flat_map(|f| f.to_le_bytes()).collect()
}

fn decode(bytes: &[u8], dim: usize) -> Option<Vec<f32>> {
    if bytes.len() != dim * 4 {
        return None;
    }
    Some(bytes.chunks_exact(4).map(|c| f32::from_le_bytes([c[0], c[1], c[2], c[3]])).collect())
}

/// Row data needed to render a result.
struct Display {
    key: Key,
    title: String,
    body: String,
}

fn load_display(conn: &Connection, ids: &[i64]) -> Result<HashMap<i64, Display>> {
    if ids.is_empty() {
        return Ok(HashMap::new());
    }
    let ph = yk_store::filter::placeholders(ids.len());
    let sql = format!(
        "SELECT id, key, json_extract(fields,'$.title'), json_extract(fields,'$.abstractNote') \
         FROM items WHERE id IN ({ph})"
    );
    let mut stmt = conn.prepare(&sql).map_err(sql_err)?;
    let mut out = HashMap::with_capacity(ids.len());
    let mut rows = stmt.query(params_from_iter(ids.iter())).map_err(sql_err)?;
    while let Some(r) = rows.next().map_err(sql_err)? {
        let id: i64 = r.get(0).map_err(sql_err)?;
        let key: String = r.get(1).map_err(sql_err)?;
        let title: Option<String> = r.get(2).map_err(sql_err)?;
        let body: Option<String> = r.get(3).map_err(sql_err)?;
        if let Ok(key) = Key::parse(&key) {
            out.insert(
                id,
                Display { key, title: title.unwrap_or_default(), body: body.unwrap_or_default() },
            );
        }
    }
    Ok(out)
}

/// Extract a short window around the first query term, marking the match.
fn snippet(display: &Display, terms: &[String]) -> Option<String> {
    const WINDOW: usize = 70;
    for source in [&display.body, &display.title] {
        if source.is_empty() {
            continue;
        }
        let lower = source.to_lowercase();
        for term in terms {
            if term.chars().count() < 2 {
                continue;
            }
            let Some(byte_at) = lower.find(&term.to_lowercase()) else { continue };
            let chars: Vec<char> = source.chars().collect();
            let at = source[..byte_at].chars().count();
            let term_len = term.chars().count();
            let end_of_match = (at + term_len).min(chars.len());
            let start = at.saturating_sub(WINDOW / 2);
            let end = (end_of_match + WINDOW / 2).min(chars.len());

            let mut out = String::new();
            if start > 0 {
                out.push('…');
            }
            out.extend(&chars[start..at]);
            out.push_str("<mark>");
            out.extend(&chars[at..end_of_match]);
            out.push_str("</mark>");
            out.extend(&chars[end_of_match..end]);
            if end < chars.len() {
                out.push('…');
            }
            return Some(out);
        }
    }
    None
}

/// Reward candidates that literally contain the query — edit distance
/// under-scores those when the title is much longer than the query.
fn substring_bonus(query: &str, title: &str) -> f32 {
    if query.is_empty() || !title.contains(query) {
        return 0.0;
    }
    let ratio = query.chars().count() as f32 / title.chars().count().max(1) as f32;
    0.6 + 0.4 * ratio
}

/// How well `query` fuzzily matches `target`.
///
/// Comparing whole strings alone is wrong: "attension" against
/// "attention is all you need" scores badly purely because the title is long.
/// So we take the best of three views — whole string, literal containment, and
/// per-token best match — which is what a human means by "close enough".
fn fuzzy_score(query: &str, target: &str) -> f32 {
    if query.is_empty() || target.is_empty() {
        return 0.0;
    }
    let mut query_tokens = text::tokenize(query);
    // Single characters match almost anything; drop them when we have better.
    if query_tokens.iter().any(|t| t.chars().count() > 1) {
        query_tokens.retain(|t| t.chars().count() > 1);
    }
    let target_tokens = text::tokenize(target);

    let token_score = if query_tokens.is_empty() || target_tokens.is_empty() {
        0.0
    } else {
        let sum: f32 = query_tokens
            .iter()
            .map(|q| {
                target_tokens.iter().map(|t| text::similarity(q, t)).fold(0.0f32, f32::max)
            })
            .sum();
        sum / query_tokens.len() as f32
    };

    text::similarity(query, target).max(substring_bonus(query, target)).max(token_score)
}

#[async_trait]
impl SearchIndex for SearchEngine {
    async fn search(&self, request: &SearchRequest) -> Result<Vec<SearchHit>> {
        let parsed = parse::ParsedQuery::parse(&request.text);
        let mut filter = request.filter.clone();
        parsed.apply_to(&mut filter);

        let query_text = parsed.text.clone();
        let mode = request.mode;
        let library_id = filter.library_id;

        // Embedding is the only step that may hit the network; do it first so
        // the database work happens in one uninterrupted blocking call.
        let query_vec = if mode.uses(SearchMode::Semantic) && !query_text.trim().is_empty() {
            match self.embedder.embed(std::slice::from_ref(&query_text)).await {
                Ok(mut v) if !v.is_empty() => Some(v.remove(0)),
                Ok(_) => None,
                Err(e) => {
                    tracing::warn!(error = %e, "semantic search unavailable, degrading");
                    None
                }
            }
        } else {
            None
        };

        let filter_for_db = filter.clone();
        let text_for_db = query_text.clone();
        // What a pure filter query will actually return, plus a little slack so
        // the caller can tell "that is the last page" from "there is more".
        let needed = (request.offset as usize)
            .saturating_add(request.limit as usize)
            .saturating_add(1)
            .min(CANDIDATE_SET);
        let (allowed_ids, keyword_hits, fuzzy_hits) = self
            .db
            .call(move |c| {
                let text_empty = text_for_db.trim().is_empty();
                // With no words to rank, the filter's own order is the answer,
                // so only a page of it is ever read.
                let want = text_empty.then_some(needed);
                let allowed = SearchEngine::allowed(c, &filter_for_db, want)?;

                let keyword = if !text_empty && mode.uses(SearchMode::Keyword) {
                    lexical::keyword(c, library_id, &text_for_db, CANDIDATES)?
                } else {
                    Vec::new()
                };

                let fuzzy = if !text_empty && mode.uses(SearchMode::Fuzzy) {
                    let norm = text::normalize(&text_for_db);
                    let mut scored: Vec<(i64, f32)> =
                        lexical::fuzzy(c, library_id, &text_for_db, CANDIDATES)?
                            .into_iter()
                            .filter_map(|cand| {
                                let s = fuzzy_score(&norm, &cand.title)
                                    .max(fuzzy_score(&norm, &cand.creator));
                                (s >= FUZZY_FLOOR).then_some((cand.id, s))
                            })
                            .collect();
                    scored.sort_unstable_by(|a, b| b.1.total_cmp(&a.1));
                    scored.truncate(CANDIDATES);
                    scored
                } else {
                    Vec::new()
                };

                Ok((allowed, keyword, fuzzy))
            })
            .await?;

        // A pure filter query (`tag:survey` with no words) is answered by the
        // filter scan itself — reused here rather than run a second time.
        let filter_only = if query_text.trim().is_empty() {
            allowed_ids.clone().unwrap_or_default()
        } else {
            Vec::new()
        };
        let allowed: Option<HashSet<i64>> =
            allowed_ids.map(|ids| ids.into_iter().collect());

        let semantic_hits = match &query_vec {
            Some(v) => self.vectors.read().search(library_id, v, CANDIDATES, allowed.as_ref()),
            None => Vec::new(),
        };

        let keep = |hits: Vec<(i64, f32)>| -> Vec<i64> {
            hits.into_iter()
                .filter(|(id, _)| allowed.as_ref().map(|a| a.contains(id)).unwrap_or(true))
                .map(|(id, _)| id)
                .collect()
        };

        let lists = vec![
            RankedList { source: MatchSource::Keyword, weight: W_KEYWORD, ids: keep(keyword_hits) },
            RankedList {
                source: MatchSource::Semantic,
                weight: W_SEMANTIC,
                ids: keep(semantic_hits),
            },
            RankedList { source: MatchSource::Fuzzy, weight: W_FUZZY, ids: keep(fuzzy_hits) },
            RankedList { source: MatchSource::Tag, weight: 1.0, ids: filter_only },
        ];
        let fused = fusion::fuse(&lists);

        let start = request.offset as usize;
        let page: Vec<fusion::Fused> =
            fused.into_iter().skip(start).take(request.limit as usize).collect();
        if page.is_empty() {
            return Ok(Vec::new());
        }

        let ids: Vec<i64> = page.iter().map(|f| f.id).collect();
        let displays = self.db.call(move |c| load_display(c, &ids)).await?;

        let terms: Vec<String> = if request.highlight {
            let mut t = text::tokenize(&query_text);
            t.extend(parsed.phrases.iter().cloned());
            t
        } else {
            Vec::new()
        };

        Ok(page
            .into_iter()
            .filter_map(|f| {
                let d = displays.get(&f.id)?;
                Some(SearchHit {
                    key: d.key.clone(),
                    score: f.score,
                    snippet: if terms.is_empty() { None } else { snippet(d, &terms) },
                    sources: f.sources,
                })
            })
            .collect())
    }

    async fn similar(&self, library_id: i64, key: &Key, k: usize) -> Result<Vec<(Key, f32)>> {
        let wanted = key.to_string();
        let id: Option<i64> = self
            .db
            .call(move |c| {
                Ok(c.query_row(
                    "SELECT id FROM items WHERE library_id=?1 AND key=?2",
                    params![library_id, wanted],
                    |r| r.get(0),
                )
                .ok())
            })
            .await?;
        let Some(id) = id else { return Ok(Vec::new()) };

        let hits = self.similar(library_id, id, k);
        if hits.is_empty() {
            return Ok(Vec::new());
        }

        // Back to keys, which is the only identifier anything outside this
        // crate is allowed to know about.
        let ids: Vec<i64> = hits.iter().map(|(id, _)| *id).collect();
        let keys = self
            .db
            .call(move |c| {
                let mut out = std::collections::HashMap::new();
                let places = vec!["?"; ids.len()].join(",");
                let mut stmt = c
                    .prepare(&format!("SELECT id, key FROM items WHERE id IN ({places})"))
                    .map_err(sql_err)?;
                let rows = stmt
                    .query_map(rusqlite::params_from_iter(ids), |r| {
                        Ok((r.get::<_, i64>(0)?, r.get::<_, String>(1)?))
                    })
                    .map_err(sql_err)?;
                for row in rows {
                    let (id, key) = row.map_err(sql_err)?;
                    out.insert(id, key);
                }
                Ok(out)
            })
            .await?;

        Ok(hits
            .into_iter()
            .filter_map(|(id, score)| {
                Key::parse(keys.get(&id)?).ok().map(|key| (key, score))
            })
            .collect())
    }

    async fn stats(&self) -> Result<SearchStats> {
        let provider = self.embedder.id().to_string();
        let dimensions = self.embedder.dimensions();
        let documents = self
            .db
            .call(|c| {
                c.query_row("SELECT count(*) FROM items WHERE deleted = 0", [], |r| r.get(0))
                    .map_err(sql_err)
            })
            .await?;
        Ok(SearchStats { documents, embedded: self.vectors.read().len() as i64, dimensions, provider })
    }

    async fn embed_pending(&self, batch: u32) -> Result<u32> {
        let rows: Vec<(i64, i64, String, String)> = self
            .db
            .call(move |c| {
                let mut stmt = c
                    .prepare_cached(
                        "SELECT item_id, library_id, text, content_hash FROM embed_queue \
                         ORDER BY queued_at LIMIT ?1",
                    )
                    .map_err(sql_err)?;
                let out = stmt
                    .query_map(params![batch], |r| Ok((r.get(0)?, r.get(1)?, r.get(2)?, r.get(3)?)))
                    .map_err(sql_err)?
                    .collect::<rusqlite::Result<Vec<_>>>()
                    .map_err(sql_err);
                out
            })
            .await?;

        if rows.is_empty() {
            return Ok(0);
        }

        let texts: Vec<String> = rows.iter().map(|r| r.2.clone()).collect();
        let vectors = self.embedder.embed(&texts).await?;
        if vectors.len() != rows.len() {
            return Err(Error::Search("embedding provider returned the wrong count".into()));
        }

        {
            let mut cache = self.vectors.write();
            for ((id, lib, _, _), v) in rows.iter().zip(&vectors) {
                cache.upsert(*id, *lib, v);
            }
        }

        let provider = self.embedder.id().to_string();
        let dim = self.embedder.dimensions();
        let payload: Vec<(i64, i64, String, Vec<u8>)> = rows
            .iter()
            .zip(&vectors)
            .map(|((id, lib, _, hash), v)| (*id, *lib, hash.clone(), encode(v)))
            .collect();
        let n = payload.len() as u32;

        // Persist in small transactions. This is a background job: it must
        // release the single SQLite write lock often enough that interactive
        // writes never queue behind it. One big transaction here starves the
        // API — an earlier version did exactly that.
        for chunk in payload.chunks(WRITE_CHUNK) {
            let chunk = chunk.to_vec();
            let provider = provider.clone();
            self.db
                .call(move |c| {
                    let tx = write_tx(c)?;
                    for (id, lib, hash, blob) in chunk {
                        tx.execute(
                            "INSERT INTO item_vectors(item_id, library_id, provider, dim, content_hash, vec)
                             VALUES (?1,?2,?3,?4,?5,?6)
                             ON CONFLICT(item_id) DO UPDATE SET
                                library_id = excluded.library_id, provider = excluded.provider,
                                dim = excluded.dim, content_hash = excluded.content_hash,
                                vec = excluded.vec",
                            params![id, lib, provider, dim as i64, hash, blob],
                        )
                        .map_err(sql_err)?;
                        tx.execute("DELETE FROM embed_queue WHERE item_id = ?1", params![id])
                            .map_err(sql_err)?;
                    }
                    tx.commit().map_err(sql_err)?;
                    Ok(())
                })
                .await?;
            // Give any waiting writer a turn before grabbing the lock again.
            tokio::task::yield_now().await;
        }

        Ok(n)
    }

    async fn reindex(&self, library_id: i64) -> Result<u64> {
        let n = self.store.rebuild_index(library_id).await?;
        self.load_vectors()?;
        Ok(n)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use yk_core::model::{Creator, ItemDraft, ItemTag};

    fn engine() -> (SearchEngine, Store, i64) {
        let store = Store::in_memory().unwrap();
        let lib = store.default_library;
        let engine = SearchEngine::new(store.clone(), Arc::new(LocalEmbedder::new())).unwrap();
        (engine, store, lib)
    }

    async fn seed(store: &Store, lib: i64) {
        let docs: [(&str, &str, &str, &str); 4] = [
            (
                "Attention Is All You Need",
                "We propose the Transformer, a network architecture based solely on attention.",
                "Vaswani",
                "transformer",
            ),
            (
                "Denoising Diffusion Probabilistic Models",
                "We present high quality image synthesis results using diffusion models.",
                "Ho",
                "diffusion",
            ),
            (
                "扩散模型在分子生成中的应用综述",
                "本文综述了扩散模型用于三维分子构象生成的最新进展。",
                "张伟",
                "综述",
            ),
            (
                "A History of Medieval Agriculture",
                "Crop rotation practices in eleventh century Europe.",
                "Smith",
                "history",
            ),
        ];
        for (title, abs, author, tag) in docs {
            let mut d = ItemDraft::new("journalArticle")
                .with_field("title", title)
                .with_field("abstractNote", abs)
                .with_field("date", "2021")
                .with_creator(Creator { last_name: Some(author.into()), ..Default::default() });
            d.tags = vec![ItemTag::manual(tag)];
            store.items.create(lib, d).await.unwrap();
        }
    }

    fn req(lib: i64, text: &str, mode: SearchMode) -> SearchRequest {
        SearchRequest {
            text: text.into(),
            mode,
            filter: ItemFilter { library_id: lib, ..Default::default() },
            limit: 20,
            offset: 0,
            highlight: true,
        }
    }

    async fn titles(e: &SearchEngine, s: &Store, lib: i64, r: SearchRequest) -> Vec<String> {
        let hits = e.search(&r).await.unwrap();
        let mut out = Vec::new();
        for h in hits {
            out.push(s.items.get(lib, &h.key).await.unwrap().title().to_string());
        }
        out
    }

    /// The structural set is now bounded by what the page needs, so paging a
    /// pure filter query is exactly what that bound could have broken.
    #[tokio::test]
    async fn a_tag_only_query_pages_all_the_way_through() {
        let (e, s, lib) = engine();
        for i in 0..25 {
            let mut draft = yk_core::model::ItemDraft::new("journalArticle")
                .with_field("title", format!("Tagged {i:02}"));
            draft.tags = vec![yk_core::model::ItemTag::manual("shelf")];
            s.items.create(lib, draft).await.unwrap();
        }

        let page = |offset: u32, limit: u32| {
            let mut r = req(lib, "tag:shelf", SearchMode::Hybrid);
            r.offset = offset;
            r.limit = limit;
            r
        };

        let first: Vec<_> =
            e.search(&page(0, 10)).await.unwrap().into_iter().map(|h| h.key).collect();
        let second: Vec<_> =
            e.search(&page(10, 10)).await.unwrap().into_iter().map(|h| h.key).collect();
        let third: Vec<_> =
            e.search(&page(20, 10)).await.unwrap().into_iter().map(|h| h.key).collect();

        assert_eq!(first.len(), 10);
        assert_eq!(second.len(), 10);
        assert_eq!(third.len(), 5, "the last page is short, not empty");

        // Every item, once. A bound that was off by one would show up here as a
        // gap between pages or a repeat across them.
        let mut all: Vec<_> = first.into_iter().chain(second).chain(third).collect();
        let before = all.len();
        all.sort();
        all.dedup();
        assert_eq!(all.len(), before, "pages overlapped");
        assert_eq!(all.len(), 25, "pages skipped something");
    }

    #[tokio::test]
    async fn a_tag_query_with_words_still_ranks_across_the_library() {
        // With words, the structural ids are a restriction rather than the
        // answer, and a hit can sit anywhere in the library — so that set must
        // not shrink to a page.
        let (e, s, lib) = engine();
        seed(&s, lib).await;
        for i in 0..30 {
            let mut draft = yk_core::model::ItemDraft::new("journalArticle")
                .with_field("title", format!("Filler {i:02}"));
            draft.tags = vec![yk_core::model::ItemTag::manual("ml")];
            s.items.create(lib, draft).await.unwrap();
        }
        let mut needle = yk_core::model::ItemDraft::new("journalArticle")
            .with_field("title", "Retrieval augmented generation");
        needle.tags = vec![yk_core::model::ItemTag::manual("ml")];
        s.items.create(lib, needle).await.unwrap();

        let mut r = req(lib, "tag:ml retrieval", SearchMode::Keyword);
        r.limit = 5;
        let t = titles(&e, &s, lib, r).await;
        assert!(t.iter().any(|x| x == "Retrieval augmented generation"), "got {t:?}");
    }

    #[tokio::test]
    async fn keyword_search_finds_exact_terms() {
        let (e, s, lib) = engine();
        seed(&s, lib).await;
        let t = titles(&e, &s, lib, req(lib, "attention", SearchMode::Keyword)).await;
        assert_eq!(t[0], "Attention Is All You Need");
    }

    #[tokio::test]
    async fn keyword_search_handles_chinese() {
        let (e, s, lib) = engine();
        seed(&s, lib).await;
        let t = titles(&e, &s, lib, req(lib, "扩散模型", SearchMode::Keyword)).await;
        assert!(t.iter().any(|x| x.contains("扩散模型")), "got {t:?}");
    }

    #[tokio::test]
    async fn fuzzy_search_tolerates_typos() {
        let (e, s, lib) = engine();
        seed(&s, lib).await;
        let t = titles(&e, &s, lib, req(lib, "attension", SearchMode::Fuzzy)).await;
        assert!(t.iter().any(|x| x == "Attention Is All You Need"), "got {t:?}");
    }

    #[tokio::test]
    async fn semantic_search_returns_related_items() {
        let (e, s, lib) = engine();
        seed(&s, lib).await;
        e.embed_pending(100).await.unwrap();
        let t =
            titles(&e, &s, lib, req(lib, "image synthesis with denoising", SearchMode::Semantic))
                .await;
        assert!(!t.is_empty());
        assert_eq!(t[0], "Denoising Diffusion Probabilistic Models", "got {t:?}");
    }

    #[tokio::test]
    async fn tag_operator_filters_results() {
        let (e, s, lib) = engine();
        seed(&s, lib).await;
        let t = titles(&e, &s, lib, req(lib, "tag:综述", SearchMode::Hybrid)).await;
        assert_eq!(t.len(), 1, "got {t:?}");
        assert!(t[0].contains("综述"));
    }

    #[tokio::test]
    async fn negated_tag_excludes_results() {
        let (e, s, lib) = engine();
        seed(&s, lib).await;
        let all = titles(&e, &s, lib, req(lib, "tag:diffusion", SearchMode::Hybrid)).await;
        assert_eq!(all.len(), 1);
        let none =
            titles(&e, &s, lib, req(lib, "tag:diffusion -tag:diffusion", SearchMode::Hybrid)).await;
        assert!(none.is_empty());
    }

    #[tokio::test]
    async fn hybrid_fuses_multiple_strategies() {
        let (e, s, lib) = engine();
        seed(&s, lib).await;
        e.embed_pending(100).await.unwrap();
        let hits = e.search(&req(lib, "diffusion models", SearchMode::Hybrid)).await.unwrap();
        assert!(!hits.is_empty());
        assert!(hits.iter().any(|h| h.sources.len() >= 2), "fusion should agree somewhere");
    }

    #[tokio::test]
    async fn snippets_mark_the_match() {
        let (e, s, lib) = engine();
        seed(&s, lib).await;
        let hits = e.search(&req(lib, "transformer", SearchMode::Keyword)).await.unwrap();
        let snip = hits[0].snippet.as_deref().unwrap_or_default();
        assert!(snip.contains("<mark>"), "got {snip:?}");
    }

    #[tokio::test]
    async fn embedding_is_incremental() {
        let (e, s, lib) = engine();
        seed(&s, lib).await;
        assert_eq!(e.embed_pending(100).await.unwrap(), 4);
        assert_eq!(e.embed_pending(100).await.unwrap(), 0, "queue drains");
        assert_eq!(e.stats().await.unwrap().embedded, 4);
    }

    #[tokio::test]
    async fn trashed_items_disappear_from_search() {
        let (e, s, lib) = engine();
        seed(&s, lib).await;
        let hit = e.search(&req(lib, "attention", SearchMode::Keyword)).await.unwrap();
        s.items.set_trashed(lib, &[hit[0].key.clone()], true).await.unwrap();
        let after = e.search(&req(lib, "attention", SearchMode::Keyword)).await.unwrap();
        assert!(after.is_empty());
    }

    #[tokio::test]
    async fn reindex_restores_a_wiped_index() {
        let (e, s, lib) = engine();
        seed(&s, lib).await;
        s.db()
            .call(|c| {
                c.execute("DELETE FROM items_fts", []).map_err(sql_err)?;
                Ok(())
            })
            .await
            .unwrap();
        assert!(e.search(&req(lib, "attention", SearchMode::Keyword)).await.unwrap().is_empty());
        assert_eq!(e.reindex(lib).await.unwrap(), 4);
        assert!(!e.search(&req(lib, "attention", SearchMode::Keyword)).await.unwrap().is_empty());
    }

    #[tokio::test]
    async fn empty_query_with_no_filter_returns_nothing() {
        let (e, s, lib) = engine();
        seed(&s, lib).await;
        assert!(e.search(&req(lib, "", SearchMode::Hybrid)).await.unwrap().is_empty());
    }

    #[tokio::test]
    async fn collection_scope_restricts_results() {
        let (e, s, lib) = engine();
        seed(&s, lib).await;
        let coll = s
            .collections
            .create(lib, yk_core::model::CollectionDraft { name: "Focus".into(), ..Default::default() })
            .await
            .unwrap();
        let all = e.search(&req(lib, "models", SearchMode::Keyword)).await.unwrap();
        assert!(!all.is_empty());

        let mut scoped = req(lib, "models", SearchMode::Keyword);
        scoped.filter.collection = Some(coll.key.clone());
        assert!(e.search(&scoped).await.unwrap().is_empty(), "empty collection has no hits");

        s.items.add_to_collection(lib, &coll.key, &[all[0].key.clone()]).await.unwrap();
        assert_eq!(e.search(&scoped).await.unwrap().len(), 1);
    }
}
